name: build_erfan

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://android.googleapis.com/packages/ota-api/vsmart_v620a_v620aopen/f43a5601e88c83632682717a5a45c933f959feb3.zip
  ROM_NAME: test.zip
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Clone ErfanGSI Source Code
         run: git clone https://github.com/together08/JvlongGSIs.git --depth=1
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 JvlongGSIs
              cd JvlongGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./JvlongGSIs/make.sh $ROM_URL Generic
        
       - name: 7z AB GSI
         run: 7za a -t7z -r JvlongGSIs/output/*JvlongGSI-AB*.img
       - name: Upload AB GSI to WeTransfer
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer we $ROM_NAME
